package org.optaplanner.optapy.translator;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Parameter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicReference;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

public class PythonBytecodeToJavaBytecodeTranslator {
    /**
     * The ASM generated bytecode. Used by
     * asmClassLoader to create the Java versions of Python methods
     */
    private static final Map<String, byte[]> classNameToBytecode = new HashMap<>();
    private static long generatedClassId = 0L;

    /**
     * A custom classloader that looks for the class in
     * classNameToBytecode
     */
    static ClassLoader asmClassLoader = new ClassLoader() {
        // getName() is an abstract method in Java 11 but not in Java 8
        public String getName() {
            return "OptaPlanner Gizmo Python Bytecode ClassLoader";
        }

        @Override
        public Class<?> findClass(String name) throws ClassNotFoundException {
            if (classNameToBytecode.containsKey(name)) {
                // Gizmo generated class
                byte[] byteCode = classNameToBytecode.get(name);
                return defineClass(name, byteCode, 0, byteCode.length);
            } else {
                // Not a Gizmo generated class; load from parent class loader
                return PythonBytecodeToJavaBytecodeTranslator.class.getClassLoader().loadClass(name);
            }
        }
    };

    private static Method getFunctionalInterfaceMethod(Class<?> interfaceClass) {
        List<Method> candidateList = new ArrayList<>();
        for (Method method : interfaceClass.getMethods()) {
            if (Modifier.isAbstract(method.getModifiers())) {
                candidateList.add(method);
            }
        }

        if (candidateList.isEmpty()) {
            throw new IllegalArgumentException("Class (" + interfaceClass.getName() + ") is not a functional interface: " +
                    "it has no abstract methods.");
        }

        if (candidateList.size() > 1) {
            throw new IllegalArgumentException("Class (" + interfaceClass.getName() + ") is not a functional interface: " +
                    "it has multiple abstract methods (" + candidateList + ").");
        }

        return candidateList.get(0);
    }

    @SuppressWarnings({ "unused", "unchecked" })
    public static <T> T translatePythonBytecode(PythonCompiledFunction pythonCompiledFunction,
            Class<T> javaFunctionalInterfaceType) {
        Method functionalMethod = getFunctionalInterfaceMethod(javaFunctionalInterfaceType);
        String className = "org.optaplanner.optapy.generated." + "function" + generatedClassId + ".GeneratedFunction";
        generatedClassId++;

        String internalClassName = className.replace('.', '/');
        AtomicReference<byte[]> classBytecodeHolder = new AtomicReference<>();
        ClassWriter classWriter = new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);
        classWriter.visit(Opcodes.V11, Modifier.PUBLIC, internalClassName, null, Type.getInternalName(Object.class),
                new String[] { Type.getInternalName(javaFunctionalInterfaceType) });
        Class<?>[] exceptionTypes = functionalMethod.getExceptionTypes();
        String[] exceptionNames = new String[exceptionTypes.length];
        for (int i = 0; i < exceptionTypes.length; i++) {
            exceptionNames[i] = Type.getInternalName(exceptionTypes[i]);
        }
        createConstructor(classWriter);
        MethodVisitor methodVisitor = classWriter.visitMethod(Modifier.PUBLIC,
                functionalMethod.getName(),
                Type.getMethodDescriptor(functionalMethod),
                null,
                exceptionNames);
        translatePythonBytecodeToMethod(functionalMethod, methodVisitor, pythonCompiledFunction);
        classWriter.visitEnd();

        classNameToBytecode.put(className, classWriter.toByteArray());

        try {
            return (T) asmClassLoader.loadClass(className).getConstructor().newInstance();
        } catch (ClassNotFoundException | InvocationTargetException | InstantiationException | IllegalAccessException
                | NoSuchMethodException e) {
            throw new IllegalStateException("Impossible State: Unable to create instance of generated class (" +
                    className + ") despite it being just generated.", e);
        }
    }

    private static void createConstructor(ClassWriter classWriter) {
        MethodVisitor methodVisitor = classWriter.visitMethod(Modifier.PUBLIC, "<init>", "()V",
                null, null);
        methodVisitor.visitCode();
        methodVisitor.visitVarInsn(Opcodes.ALOAD, 0);
        methodVisitor.visitMethodInsn(Opcodes.INVOKESPECIAL, Type.getInternalName(Object.class), "<init>",
                "()V", false);
        methodVisitor.visitInsn(Opcodes.RETURN);
        methodVisitor.visitMaxs(-1, -1);
        methodVisitor.visitEnd();
    }

    private static void translatePythonBytecodeToMethod(Method method, MethodVisitor methodVisitor,
            PythonCompiledFunction pythonCompiledFunction) {
        for (Parameter parameter : method.getParameters()) {
            methodVisitor.visitParameter(parameter.getName(), 0);
        }
        methodVisitor.visitCode();

        Map<Integer, Label> bytecodeCounterToLabelMap = new HashMap<>();
        LocalVariableHelper localVariableHelper = new LocalVariableHelper(method.getParameters(), pythonCompiledFunction);

        for (int i = 0; i < localVariableHelper.parameters.length; i++) {
            copyParameter(methodVisitor, localVariableHelper, i);
        }

        for (PythonBytecodeInstruction instruction : pythonCompiledFunction.instructionList) {
            translatePythonBytecodeInstruction(method, methodVisitor, pythonCompiledFunction, instruction,
                    bytecodeCounterToLabelMap, localVariableHelper);
        }
        methodVisitor.visitMaxs(-1, -1);
        methodVisitor.visitEnd();
    }

    public enum CompareOp {
        LESS_THAN(0),
        LESS_THAN_OR_EQUALS(1),
        EQUALS(2),
        NOT_EQUALS(3),
        GREATER_THAN(4),
        GREATER_THAN_OR_EQUALS(5);

        public final int id;

        CompareOp(int id) {
            this.id = id;
        }

        static CompareOp getOp(int id) {
            for (CompareOp op : CompareOp.values()) {
                if (op.id == id) {
                    return op;
                }
            }
            throw new IllegalArgumentException("No Op corresponds to id (" + id + ")");
        }
    }

    private static class LocalVariableHelper {
        final Parameter[] parameters;
        final int parameterSlotsEnd;
        final int pythonLocalVariablesSlotEnd;
        int usedLocals;

        public LocalVariableHelper(Parameter[] parameters, PythonCompiledFunction compiledFunction) {
            this.parameters = parameters;
            int slotsUsedByParameters = 1;
            boolean isAnyPrimitive = false;
            for (Parameter parameter : parameters) {
                if (parameter.getType().equals(long.class) || parameter.getType().equals(double.class)) {
                    slotsUsedByParameters += 2;
                } else {
                    slotsUsedByParameters += 1;
                }
                isAnyPrimitive |= parameter.getType().isPrimitive();
            }
            parameterSlotsEnd = slotsUsedByParameters;
            pythonLocalVariablesSlotEnd = parameterSlotsEnd + compiledFunction.co_varnames.size();
        }

        public int getParameterSlot(int parameterIndex) {
            if (parameterIndex > parameters.length) {
                throw new IndexOutOfBoundsException("Asked for the slot corresponding to the (" + parameterIndex + ") " +
                        "parameter, but there are only (" + parameters.length + ") parameters (" + Arrays.toString(parameters)
                        + ").");
            }
            int slotsUsedByParameters = 1;
            for (int i = 0; i < parameterIndex; i++) {
                if (parameters[i].getType().equals(long.class) || parameters[i].getType().equals(double.class)) {
                    slotsUsedByParameters += 2;
                } else {
                    slotsUsedByParameters += 1;
                }
            }
            return slotsUsedByParameters;
        }

        public int getPythonLocalVariableSlot(int index) {
            return parameterSlotsEnd + index;
        }

        public int newLocal() {
            int slot = pythonLocalVariablesSlotEnd + usedLocals;
            usedLocals++;
            return slot;
        }

        public void freeLocal() {
            usedLocals--;
        }
    }

    private static void loadConstant(MethodVisitor methodVisitor, Object constant) {
        if (constant == null) {
            methodVisitor.visitInsn(Opcodes.ACONST_NULL);
            return;
        }

        if (constant instanceof Number || constant instanceof String) {
            methodVisitor.visitLdcInsn(constant);
            return;
        }

        if (constant instanceof Boolean) {
            if (Boolean.TRUE.equals(constant)) {
                methodVisitor.visitFieldInsn(Opcodes.GETSTATIC, Type.getInternalName(Boolean.class),
                        "TRUE", Type.getDescriptor(Boolean.class));
            } else {
                methodVisitor.visitFieldInsn(Opcodes.GETSTATIC, Type.getInternalName(Boolean.class),
                        "FALSE", Type.getDescriptor(Boolean.class));
            }
            return;
        }
        throw new UnsupportedOperationException("Cannot load constant (" + constant + ").");
    }

    private static void compareValues(MethodVisitor methodVisitor, CompareOp op) {
        switch (op) {
            case EQUALS:
            case NOT_EQUALS:
                methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, Type.getInternalName(Objects.class),
                        "equals", Type.getMethodDescriptor(Type.getType(boolean.class),
                                Type.getType(Object.class),
                                Type.getType(Object.class)),
                        false);
                break;
            default:
                methodVisitor.visitMethodInsn(Opcodes.INVOKEINTERFACE, Type.getInternalName(Comparable.class),
                        "compareTo", Type.getMethodDescriptor(Type.getType(int.class),
                                Type.getType(Object.class)),
                        true);
                break;
        }

        if (op.equals(CompareOp.EQUALS) || op.equals(CompareOp.NOT_EQUALS)) {
            if (op.equals(CompareOp.NOT_EQUALS)) {
                methodVisitor.visitInsn(Opcodes.ICONST_1);
                methodVisitor.visitInsn(Opcodes.IXOR);
            }
            methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, Type.getInternalName(Boolean.class),
                    "valueOf", Type.getMethodDescriptor(Type.getType(Boolean.class),
                            Type.getType(boolean.class)),
                    false);
            return;
        }

        int compareToOpcode;
        methodVisitor.visitInsn(Opcodes.ICONST_0);

        switch (op) {
            case LESS_THAN:
                compareToOpcode = Opcodes.IF_ICMPLT;
                break;
            case LESS_THAN_OR_EQUALS:
                compareToOpcode = Opcodes.IF_ICMPLE;
                break;
            case GREATER_THAN:
                compareToOpcode = Opcodes.IF_ICMPGT;
                break;
            case GREATER_THAN_OR_EQUALS:
                compareToOpcode = Opcodes.IF_ICMPGE;
                break;

            default:
                throw new IllegalStateException("Impossible State: unmatched case for (" + op + ").");
        }

        Label ifTrue = new Label();
        Label afterEnd = new Label();

        methodVisitor.visitJumpInsn(compareToOpcode, ifTrue);
        methodVisitor.visitInsn(Opcodes.ICONST_0);
        methodVisitor.visitJumpInsn(Opcodes.GOTO, afterEnd);
        methodVisitor.visitLabel(ifTrue);
        methodVisitor.visitInsn(Opcodes.ICONST_1);
        methodVisitor.visitLabel(afterEnd);
        methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, Type.getInternalName(Boolean.class),
                "valueOf", Type.getMethodDescriptor(Type.getType(Boolean.class),
                        Type.getType(boolean.class)),
                false);
    }

    private static void buildCollection(Class<? extends Collection> collectionType, MethodVisitor methodVisitor,
            int itemCount) {
        String typeInternalName = Type.getInternalName(collectionType);
        methodVisitor.visitTypeInsn(Opcodes.NEW, typeInternalName);
        methodVisitor.visitInsn(Opcodes.DUP);
        methodVisitor.visitMethodInsn(Opcodes.INVOKESPECIAL, typeInternalName, "<init>", "()V", false);

        for (int i = 0; i < itemCount; i++) {
            methodVisitor.visitInsn(Opcodes.DUP_X1);
            methodVisitor.visitInsn(Opcodes.SWAP);
            methodVisitor.visitMethodInsn(Opcodes.INVOKEINTERFACE, Type.getInternalName(Collection.class),
                    "add",
                    Type.getMethodDescriptor(Type.BOOLEAN_TYPE, Type.getType(Object.class)),
                    true);
            methodVisitor.visitInsn(Opcodes.POP);
        }

        if (List.class.isAssignableFrom(collectionType)) {
            // We built the list in reverse order, so we now need to reverse it
            methodVisitor.visitInsn(Opcodes.DUP);
            methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, Type.getInternalName(Collections.class),
                    "reverse",
                    Type.getMethodDescriptor(Type.VOID_TYPE, Type.getType(List.class)),
                    false);
        }
    }

    private static void returnValue(MethodVisitor methodVisitor, Method method) {
        Class<?> returnType = method.getReturnType();

        if (void.class.equals(returnType)) {
            methodVisitor.visitInsn(Opcodes.RETURN);
            return;
        }

        if (!returnType.isPrimitive()) {
            methodVisitor.visitInsn(Opcodes.ARETURN);
            return;
        }

        String wrapperClassName;
        String methodName;
        String methodDescriptor;
        int returnOpcode;

        if (boolean.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Boolean.class);
            methodName = "booleanValue";
            methodDescriptor = Type.getMethodDescriptor(Type.BOOLEAN_TYPE);
            returnOpcode = Opcodes.IRETURN;
        } else if (char.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Number.class);
            methodName = "charValue";
            methodDescriptor = Type.getMethodDescriptor(Type.CHAR_TYPE);
            returnOpcode = Opcodes.IRETURN;
        } else if (byte.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Number.class);
            methodName = "byteValue";
            methodDescriptor = Type.getMethodDescriptor(Type.BYTE_TYPE);
            returnOpcode = Opcodes.IRETURN;
        } else if (short.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Number.class);
            methodName = "shortValue";
            methodDescriptor = Type.getMethodDescriptor(Type.SHORT_TYPE);
            returnOpcode = Opcodes.IRETURN;
        } else if (int.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Number.class);
            methodName = "intValue";
            methodDescriptor = Type.getMethodDescriptor(Type.INT_TYPE);
            returnOpcode = Opcodes.IRETURN;
        } else if (float.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Number.class);
            methodName = "floatValue";
            methodDescriptor = Type.getMethodDescriptor(Type.FLOAT_TYPE);
            returnOpcode = Opcodes.FRETURN;
        } else if (long.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Number.class);
            methodName = "longValue";
            methodDescriptor = Type.getMethodDescriptor(Type.LONG_TYPE);
            returnOpcode = Opcodes.LRETURN;
        } else if (double.class.equals(returnType)) {
            wrapperClassName = Type.getInternalName(Number.class);
            methodName = "doubleValue";
            methodDescriptor = Type.getMethodDescriptor(Type.DOUBLE_TYPE);
            returnOpcode = Opcodes.DRETURN;
        } else {
            throw new IllegalStateException("Unhandled case for primitive type (" + returnType + ").");
        }

        methodVisitor.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                wrapperClassName, methodName, methodDescriptor,
                false);
        methodVisitor.visitInsn(returnOpcode);
    }

    private static void copyParameter(MethodVisitor methodVisitor, LocalVariableHelper localVariableHelper,
            int parameterIndex) {
        Class<?> parameterClass = localVariableHelper.parameters[parameterIndex].getType();
        if (parameterClass.isPrimitive()) {
            int loadOpcode;
            String valueOfOwner;
            String valueOfDescriptor;

            if (boolean.class.equals(parameterClass)) {
                loadOpcode = Opcodes.ILOAD;
                valueOfOwner = Type.getInternalName(Integer.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Boolean.class), Type.getType(boolean.class));
            } else if (char.class.equals(parameterClass)) {
                loadOpcode = Opcodes.ILOAD;
                valueOfOwner = Type.getInternalName(Character.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Character.class), Type.getType(char.class));
            } else if (byte.class.equals(parameterClass)) {
                loadOpcode = Opcodes.ILOAD;
                valueOfOwner = Type.getInternalName(Byte.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Byte.class), Type.getType(byte.class));
            } else if (short.class.equals(parameterClass)) {
                loadOpcode = Opcodes.ILOAD;
                valueOfOwner = Type.getInternalName(Short.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Short.class), Type.getType(short.class));
            } else if (int.class.equals(parameterClass)) {
                loadOpcode = Opcodes.ILOAD;
                valueOfOwner = Type.getInternalName(Integer.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Integer.class), Type.getType(int.class));
            } else if (float.class.equals(parameterClass)) {
                loadOpcode = Opcodes.FLOAD;
                valueOfOwner = Type.getInternalName(Float.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Float.class), Type.getType(float.class));
            } else if (long.class.equals(parameterClass)) {
                loadOpcode = Opcodes.LLOAD;
                valueOfOwner = Type.getInternalName(Long.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Long.class), Type.getType(long.class));
            } else if (double.class.equals(parameterClass)) {
                loadOpcode = Opcodes.DLOAD;
                valueOfOwner = Type.getInternalName(Double.class);
                valueOfDescriptor = Type.getMethodDescriptor(Type.getType(Double.class), Type.getType(double.class));
            } else {
                throw new IllegalStateException("Unhandled case for primitive type (" + parameterClass + ").");
            }

            methodVisitor.visitVarInsn(loadOpcode, localVariableHelper.getParameterSlot(parameterIndex));
            methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, valueOfOwner, "valueOf",
                    valueOfDescriptor, false);
            methodVisitor.visitVarInsn(Opcodes.ASTORE, localVariableHelper.getPythonLocalVariableSlot(parameterIndex));
        } else {
            methodVisitor.visitVarInsn(Opcodes.ALOAD, localVariableHelper.getParameterSlot(parameterIndex));
            methodVisitor.visitVarInsn(Opcodes.ASTORE, localVariableHelper.getPythonLocalVariableSlot(parameterIndex));
        }
    }

    private static void translatePythonBytecodeInstruction(Method method, MethodVisitor methodVisitor,
            PythonCompiledFunction pythonCompiledFunction,
            PythonBytecodeInstruction instruction,
            Map<Integer, Label> bytecodeCounterToLabelMap,
            LocalVariableHelper localVariableHelper) {
        if (instruction.isJumpTarget) {
            Label label = bytecodeCounterToLabelMap.computeIfAbsent(instruction.offset, offset -> new Label());
            methodVisitor.visitLabel(label);
        }
        switch (instruction.opcode) {
            case NOP: { // use brackets to scope local variables
                methodVisitor.visitInsn(Opcodes.NOP);
                break;
            }
            case POP_TOP: {
                methodVisitor.visitInsn(Opcodes.POP);
                break;
            }
            case ROT_TWO: {
                methodVisitor.visitInsn(Opcodes.SWAP);
                break;
            }
            case ROT_THREE: {
                methodVisitor.visitInsn(Opcodes.DUP_X2);
                methodVisitor.visitInsn(Opcodes.POP);
                break;
            }
            case ROT_FOUR: {
                int secondFromStack = localVariableHelper.newLocal();
                int thirdFromStack = localVariableHelper.newLocal();
                Label localsStart = new Label();
                Label localsEnd = new Label();

                methodVisitor.visitInsn(Opcodes.DUP_X2);
                methodVisitor.visitInsn(Opcodes.POP);

                methodVisitor.visitLabel(localsStart);
                methodVisitor.visitVarInsn(Opcodes.ASTORE, secondFromStack);
                methodVisitor.visitVarInsn(Opcodes.ASTORE, thirdFromStack);
                methodVisitor.visitInsn(Opcodes.SWAP);
                methodVisitor.visitVarInsn(Opcodes.ALOAD, thirdFromStack);
                methodVisitor.visitVarInsn(Opcodes.ALOAD, secondFromStack);
                methodVisitor.visitLabel(localsEnd);

                localVariableHelper.freeLocal();
                localVariableHelper.freeLocal();
                break;
            }
            case DUP_TOP: {
                methodVisitor.visitInsn(Opcodes.DUP);
                break;
            }
            case DUP_TOP_TWO: {
                methodVisitor.visitInsn(Opcodes.DUP2);
                break;
            }
            case UNARY_POSITIVE: {
                break;
            }
            case UNARY_NEGATIVE: {
                break;
            }
            case UNARY_NOT:
                break;
            case UNARY_INVERT:
                break;
            case GET_ITER:
                break;
            case GET_YIELD_FROM_ITER:
                break;
            case BINARY_POWER:
                break;
            case BINARY_MULTIPLY:
                break;
            case BINARY_MATRIX_MULTIPLY:
                break;
            case BINARY_FLOOR_DIVIDE:
                break;
            case BINARY_TRUE_DIVIDE:
                break;
            case BINARY_MODULO:
                break;
            case BINARY_ADD:
                break;
            case BINARY_SUBTRACT:
                break;
            case BINARY_SUBSCR:
                break;
            case BINARY_LSHIFT:
                break;
            case BINARY_RSHIFT:
                break;
            case BINARY_AND:
                break;
            case BINARY_XOR:
                break;
            case BINARY_OR:
                break;
            case INPLACE_POWER:
                break;
            case INPLACE_MULTIPLY:
                break;
            case INPLACE_MATRIX_MULTIPLY:
                break;
            case INPLACE_FLOOR_DIVIDE:
                break;
            case INPLACE_TRUE_DIVIDE:
                break;
            case INPLACE_MODULO:
                break;
            case INPLACE_ADD:
                break;
            case INPLACE_SUBTRACT:
                break;
            case INPLACE_LSHIFT:
                break;
            case INPLACE_RSHIFT:
                break;
            case INPLACE_AND:
                break;
            case INPLACE_XOR:
                break;
            case INPLACE_OR:
                break;
            case STORE_SUBSCR:
                break;
            case DEL_SUBSCR:
                break;
            case GET_AWAITABLE:
                break;
            case GET_AITER:
                break;
            case GET_ANEXT:
                break;
            case END_ASYNC_FOR:
                break;
            case BEFORE_ASYNC_WITH:
                break;
            case SETUP_ASYNC_WITH:
                break;
            case PRINT_EXPR:
                break;
            case SET_ADD:
                break;
            case LIST_APPEND:
                break;
            case MAP_ADD:
                break;
            case RETURN_VALUE: {
                returnValue(methodVisitor, method);
                break;
            }
            case YIELD_VALUE:
                break;
            case YIELD_FROM:
                break;
            case SETUP_ANNOTATIONS:
                break;
            case IMPORT_STAR:
                break;
            case POP_BLOCK:
                break;
            case POP_EXCEPT:
                break;
            case RERAISE:
                break;
            case WITH_EXCEPT_START:
                break;
            case LOAD_ASSERTION_ERROR:
                break;
            case LOAD_BUILD_CLASS:
                break;
            case SETUP_WITH:
                break;
            case STORE_NAME:
                break;
            case DELETE_NAME:
                break;
            case UNPACK_SEQUENCE:
                break;
            case UNPACK_EX:
                break;
            case STORE_ATTR:
                break;
            case DELETE_ATTR:
                break;
            case STORE_GLOBAL:
                break;
            case DELETE_GLOBAL:
                break;
            case LOAD_CONST: {
                loadConstant(methodVisitor, pythonCompiledFunction.co_constants.get(instruction.arg));
                break;
            }
            case LOAD_NAME: {
                loadConstant(methodVisitor, pythonCompiledFunction.co_names.get(instruction.arg));
                break;
            }
            case BUILD_TUPLE: {
                buildCollection(ArrayList.class, methodVisitor, instruction.arg);
                methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, Type.getInternalName(Collections.class),
                        "unmodifiableList",
                        Type.getMethodDescriptor(Type.getType(List.class), Type.getType(List.class)),
                        false);
                break;
            }
            case BUILD_LIST: {
                buildCollection(ArrayList.class, methodVisitor, instruction.arg);
                break;
            }
            case BUILD_SET: {
                buildCollection(HashSet.class, methodVisitor, instruction.arg);
                break;
            }
            case BUILD_MAP:
                break;
            case BUILD_CONST_KEY_MAP:
                break;
            case BUILD_STRING:
                break;
            case LIST_TO_TUPLE:
                break;
            case LIST_EXTEND:
                break;
            case SET_UPDATE:
                break;
            case DICT_UPDATE:
                break;
            case DICT_MERGE:
                break;
            case LOAD_ATTR:
                break;
            case COMPARE_OP: {
                compareValues(methodVisitor, CompareOp.getOp(instruction.arg));
                break;
            }
            case IS_OP:
                break;
            case CONTAINS_OP:
                break;
            case IMPORT_NAME:
                break;
            case IMPORT_FROM:
                break;
            case JUMP_FORWARD:
                break;
            case POP_JUMP_IF_TRUE:
                break;
            case POP_JUMP_IF_FALSE:
                break;
            case JUMP_IF_NOT_EXC_MATCH:
                break;
            case JUMP_IF_TRUE_OR_POP:
                break;
            case JUMP_IF_FALSE_OR_POP:
                break;
            case JUMP_ABSOLUTE:
                break;
            case FOR_ITER:
                break;
            case LOAD_GLOBAL:
                break;
            case SETUP_FINALLY:
                break;
            case LOAD_FAST: {
                methodVisitor.visitVarInsn(Opcodes.ALOAD, localVariableHelper.getPythonLocalVariableSlot(instruction.arg));
                break;
            }
            case STORE_FAST: {
                methodVisitor.visitVarInsn(Opcodes.ASTORE, localVariableHelper.getPythonLocalVariableSlot(instruction.arg));
                break;
            }
            case DELETE_FAST:
                break;
            case LOAD_CLOSURE:
                break;
            case LOAD_DEREF:
                break;
            case LOAD_CLASSDEREF:
                break;
            case STORE_DEREF:
                break;
            case DELETE_DEREF:
                break;
            case RAISE_VARARGS:
                break;
            case CALL_FUNCTION:
                break;
            case CALL_FUNCTION_KW:
                break;
            case CALL_FUNCTION_EX:
                break;
            case LOAD_METHOD:
                break;
            case CALL_METHOD:
                break;
            case MAKE_FUNCTION:
                break;
            case BUILD_SLICE:
                break;
            case EXTENDED_ARG:
                break;
            case FORMAT_VALUE:
                break;
            default:
                throw new UnsupportedOperationException("Opcode not implemented: " + instruction.opname);
        }
    }
}
